export const IS_ONBOARDING_PASSED = 'isOnboardingPassed'
export const IS_ONBOARDING_SKIPPED = 'isOnboardingSkipped'
export const EXPENSES = 'expenses'
export const USER = 'user'
export const OCEAN_REWARDS_LS = 'oceanRewards'
export const RESERVATIONS = 'reservations'
